language: scala
matrix:
  include:
    - os: linux
      jdk: oraclejdk9
      scala: 2.12.6
    - os: linux
      jdk: openjdk8
      scala: 2.12.6
    - os: linux
      jdk: oraclejdk8
      scala: 2.11.12
script:
  - travis_wait 30 sbt -no-colors ++$TRAVIS_SCALA_VERSION clean coverage test coverageReport mimaReportBinaryIssues
after_success:
  - bash <(curl -s https://codecov.io/bash)
