sudo: false

dist: trusty

language: scala

scala:
  - 2.11.12
  - 2.12.4

jdk: oraclejdk8

script:
  - sbt ++$TRAVIS_SCALA_VERSION clean coverage test coverageReport
  - sbt -no-colors ++$TRAVIS_SCALA_VERSION 'benchmark/jmh:run -prof gc .*CodecBenchmark.*'

after_success:
  - bash <(curl -s https://codecov.io/bash)
