name: build

on:
  push:
    paths-ignore:
      - 'jsoniter-scala-examples/**'
      - '**.md'
    branches-ignore:
      - "gh-pages"
  pull_request:
    paths-ignore:
      - 'jsoniter-scala-examples/**'
      - '**.md'
    branches-ignore:
      - "gh-pages"

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        java:
          - graalvm@
          - amazon-corretto@1.8
          - amazon-corretto@1.11
        os:
          - ubuntu-latest
          - macOS-latest
          - windows-latest
      fail-fast: false
    steps:
      - name: Configure git
        run: "git config --global core.autocrlf false"
        shell: bash
      - uses: actions/checkout@v1
        with:
          ref: ${{ github.ref }}
          fetch-depth: 100
      - uses: actions/cache@v1
        with:
          path: ~/.ivy2
          key: ${{ runner.os }}-ivy2-${{ hashFiles('**/build.sbt') }}
      - uses: actions/cache@v1
        with:
          path: ~/.sbt
          key: ${{ runner.os }}-sbt-${{ hashFiles('**/build.properties') }}
      - uses: olafurpg/setup-scala@v5
        with:
          java-version: ${{ matrix.java }}
      - name: Compile, test and check binary compatibility
        run: "sbt -batch clean +test +mimaReportBinaryIssues"
        shell: bash
