name: build

on:
  push:
    paths-ignore:
      - 'jsoniter-scala-examples/**'
      - '**.md'
    branches-ignore:
      - "gh-pages"
  pull_request:
    paths-ignore:
      - 'jsoniter-scala-examples/**'
      - '**.md'
    branches-ignore:
      - "gh-pages"

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        java:
          - zulu@1.17
          - graalvm-ce-java11
        os:
          - macOS-latest # FIXME: restore build on Ubuntu and Windows
      fail-fast: false
    steps:
      - name: Configure git
        run: "git config --global core.autocrlf false"
        shell: bash
      - uses: actions/checkout@v3
        with:
          fetch-depth: 300
      - name: Fetch tags
        run: git fetch --depth=300 origin +refs/tags/*:refs/tags/*
      - uses: coursier/cache-action@v6
      - uses: olafurpg/setup-scala@v13
        with:
          java-version: ${{ matrix.java }}
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Test and Check Binary Compatibility
        run: "sbt -batch +test +mimaReportBinaryIssues"
        shell: bash
